version: "3"
   
services:
  app:
    image: "testapp:1.0.2"

    build: .

    ports:
      - "8000:8000"
    
    #volumes:
     # - .:/code

    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file: 
    - hello.env   
    
    depends_on:
      - db
  

  db:
    image: postgres:13-alpine
    container_name: postgres
    env_file: 
    - postgres.env   
    ports:
      - 5432:5432